import { useEffect, useMemo, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { AlertCircle, ArrowLeft, Building2, CalendarClock, CheckCircle2, Clipboard, FileCheck2, MessageSquareText, Printer, RefreshCw, Sparkles, Users } from "lucide-react";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Progress } from "@/components/ui/progress";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { ManagerFilters } from "@/components/manager/ManagerFilters";
import { NavigationMenu } from "@/components/NavigationMenu";
import { useBackNavigation } from "@/hooks/use-back-navigation";
import { useManagerPeriod } from "@/hooks/use-manager-period";
import { toast } from "@/hooks/use-toast";
import { customers, districts, documentedStrength, oneToOnePoints, signals, teamMembers, themes, type DemoScenario } from "@/data/managerDemo";
import jarvisLogo from "@/assets/jarvis-logo.svg";

type PanelKey = "contacts" | "coverage" | "documentation" | "quality" | "signals" | "themes" | "brief" | "plan" | null;
const scenarios: { value: DemoScenario; label: string }[] = [
  { value: "normal", label: "Standard" }, { value: "loading", label: "Indlæser" }, { value: "no-activity", label: "Ingen aktivitet" }, { value: "error", label: "Fejl" }, { value: "not-assessed", label: "Ikke vurderet" }, { value: "partial", label: "Delvis analyse" }, { value: "no-plan", label: "Ingen kontaktplan" }, { value: "imported-docs", label: "Importeret dokumentation" }, { value: "unknown-meeting", label: "Ukendt mødedata" }, { value: "missing-segment", label: "Ukendt segment" }, { value: "old-training", label: "Gammel træning" }, { value: "incomplete", label: "Uafsluttet periode" }, { value: "prep-error", label: "1:1-generering fejler" },
];

const SourceLink = ({ children, onClick }: { children: React.ReactNode; onClick: () => void }) => <button className="underline decoration-border underline-offset-4 hover:decoration-primary" onClick={onClick}>{children}</button>;

const EmployeeDetail = () => {
  const navigate = useNavigate();
  const back = useBackNavigation("/manager");
  const { slug } = useParams();
  const { period, setPeriod, option, hasFixture } = useManagerPeriod();
  const employee = useMemo(() => teamMembers.find((item) => item.slug === slug) ?? teamMembers[0], [slug]);
  const [scenario, setScenario] = useState<DemoScenario>(employee.scenario as DemoScenario);
  const [panel, setPanel] = useState<PanelKey>(null);
  const [prepOpen, setPrepOpen] = useState(false);
  const [selectedTheme, setSelectedTheme] = useState<(typeof themes)[number] | null>(null);
  const [selectedSignal, setSelectedSignal] = useState<(typeof signals)[number] | null>(null);
  const [customerType, setCustomerType] = useState("HCO");

  useEffect(() => setScenario(employee.scenario as DemoScenario), [employee]);
  useEffect(() => { const hash = window.location.hash.slice(1); if (hash === "signals" || hash === "themes") document.getElementById(hash)?.scrollIntoView(); if (hash === "documentation") setPanel("documentation"); }, []);

  const copyPrep = async () => {
    const text = [`1:1-forberedelse — ${employee.name}`, option.range, documentedStrength, ...oneToOnePoints.flatMap((item) => [`${item.title}: ${item.observation}`, `Spørgsmål: ${item.question}`, `Kilder: ${item.sources}`])].join("\n\n");
    await navigator.clipboard.writeText(text);
    toast({ title: "Kopieret", description: "De tre samtalepunkter og kilder er kopieret." });
  };
  const noActivity = scenario === "no-activity";
  const failed = scenario === "error";
  const partial = scenario === "partial";
  const notAssessed = scenario === "not-assessed";

  return <div className="min-h-screen bg-background">
    <header className="border-b bg-card shadow-sm"><div className="container mx-auto px-4 py-4 sm:px-6"><div className="flex min-w-0 items-center gap-2 sm:gap-3"><Button variant="ghost" size="icon" onClick={back} aria-label="Tilbage til team"><ArrowLeft className="h-5 w-5" /></Button><img src={jarvisLogo} alt="Jarvis" className="h-10 w-10 shrink-0" /><div className="min-w-0 flex-1"><h1 className="truncate font-bold">Medarbejderoverblik</h1><p className="truncate text-sm text-muted-foreground">Forberedelse til 1:1</p></div><NavigationMenu /></div><div className="mt-2 flex flex-wrap justify-end gap-x-4 gap-y-1 text-xs text-muted-foreground"><span>Data synkroniseret 2. okt 10:45</span><span>Beregnet 2. okt 10:48</span></div></div></header>
    <main className="container mx-auto space-y-8 px-4 py-7 sm:px-6">
      <ManagerFilters period={period} onPeriodChange={setPeriod} range={option.range} employee={employee.slug} onEmployeeChange={(value) => value === "all" ? navigate("/manager") : navigate(`/manager/employee/${value}`)} incomplete={scenario === "incomplete"} />
      <section className="flex flex-col gap-4 sm:flex-row sm:items-center"><div className="flex h-14 w-14 items-center justify-center rounded-full bg-primary/10 text-lg font-bold text-primary">{employee.initials}</div><div className="flex-1"><button className="mb-1 flex items-center text-sm text-primary" onClick={() => navigate("/manager")}><ArrowLeft className="mr-1 h-3.5 w-3.5" />Tilbage til team</button><h2 className="text-3xl font-bold">{employee.name}</h2><p className="text-muted-foreground">{employee.role} · {employee.district}</p></div><div className="flex flex-wrap items-end gap-3"><div><p className="mb-1 text-xs text-muted-foreground">Prototypevariant</p><Select value={scenario} onValueChange={(value) => setScenario(value as DemoScenario)}><SelectTrigger className="w-52 bg-background"><SelectValue /></SelectTrigger><SelectContent>{scenarios.map((item) => <SelectItem key={item.value} value={item.value}>{item.label}</SelectItem>)}</SelectContent></Select></div><Button onClick={() => setPrepOpen(true)}><Sparkles className="mr-2 h-4 w-4" />Forbered 1:1</Button></div></section>

      {!hasFixture ? <Card><CardContent className="p-10 text-center"><h3 className="font-semibold">Ingen forberedte demodata for denne periode</h3><p className="mt-2 text-sm text-muted-foreground">Vælg Seneste 30 dage for at se medarbejderdata.</p></CardContent></Card> : scenario === "loading" ? <div className="space-y-4" aria-label="Indlæser medarbejderdata"><div className="h-36 animate-pulse rounded-md bg-muted" /><div className="grid gap-3 sm:grid-cols-4">{[1,2,3,4].map((item) => <div key={item} className="h-32 animate-pulse rounded-md bg-muted" />)}</div></div> : failed ? <Card className="border-destructive/40"><CardContent className="p-10 text-center"><AlertCircle className="mx-auto h-9 w-9 text-destructive" /><h3 className="mt-3 font-semibold">Kunne ikke hente medarbejderdata</h3><p className="mt-2 text-sm text-muted-foreground">Der vises ikke tomme lister eller nulværdier, når opslaget fejler.</p><Button className="mt-4" onClick={() => setScenario("normal")}><RefreshCw className="mr-2 h-4 w-4" />Prøv igen</Button></CardContent></Card> : <>
        <section className="space-y-3"><div><h3 className="text-xl font-bold">Observationer i perioden</h3><p className="text-sm text-muted-foreground">Kort brief med sporbare kilder</p></div><Card className="shadow-sm"><CardContent className="p-6">{noActivity ? <p className="text-sm">Der er registreret 0 kontakter i perioden.</p> : <p className="text-sm leading-7"><SourceLink onClick={() => setPanel("contacts")}>Jonas har 62 registrerede kontakter i perioden</SourceLink>, heraf 41 fysiske og 21 virtuelle. <SourceLink onClick={() => setPanel("coverage")}>34 af 71 tildelte HCO'er har en registreret kontakt</SourceLink>. <SourceLink onClick={() => setPanel("documentation")}>Dokumentation foreligger for 58 af 62 kontakter</SourceLink>; tre er kladder, én er uden dokumentation, og to er klar, men ikke sendt. <SourceLink onClick={() => setPanel("quality")}>Debriefkvaliteten er 6,8 baseret på 39 vurderede debriefs</SourceLink>. <SourceLink onClick={() => setPanel("themes")}>Spørgsmål om opstart af Dose 1 optræder i 14 analyserede debriefs</SourceLink>. De næste samtaler kan tage udgangspunkt i disse kundespørgsmål og de aktuelle kundesignaler.</p>}<p className="mt-3 text-xs text-muted-foreground">Baseret på {noActivity ? "0 registrerede kontakter" : "62 registrerede kontakter og 51 analyserede debriefs"}</p></CardContent></Card></section>

        <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[
          [Users, "Registrerede kontakter", noActivity ? "0" : "62", noActivity ? "" : "41 fysiske · 21 virtuelle", noActivity ? "" : "Telefonkontakt: 18", noActivity || scenario === "incomplete" ? "" : "+8 mod forrige periode", "contacts"],
          [Building2, "Kundebredde", noActivity ? "0 / 71" : "34 / 71", "Tildelte HCO'er med kontakt", noActivity ? "" : "48 %", noActivity || scenario === "incomplete" ? "" : "+5 procentpoint", "coverage"],
          [FileCheck2, "Dokumentation foreligger", noActivity ? "0 / 0" : "58 / 62", noActivity ? "Ingen relevante kontakter" : scenario === "imported-docs" ? "14 importeret fra CRM" : "44 Jarvis-debriefs · 14 importeret", noActivity ? "" : "3 kladder · 1 uden · 2 klar, ikke sendt", "", "documentation"],
          [MessageSquareText, "Debriefkvalitet", noActivity || notAssessed ? "Ikke vurderet" : "6,8", noActivity || notAssessed ? "Ingen vurderede debriefs" : "n = 39 af 58 dokumenterede", "", noActivity || notAssessed || scenario === "incomplete" ? "" : "+0,3 mod forrige periode (n = 22)", "quality"],
        ].map(([Icon, label, value, note, detail, trend, key]) => <button key={String(label)} className="text-left" onClick={() => setPanel(key as PanelKey)}><Card className="h-full shadow-sm transition-colors hover:bg-muted/20"><CardContent className="p-5"><Icon className="h-5 w-5 text-primary" /><p className="mt-4 text-sm text-muted-foreground">{String(label)}</p><p className="mt-1 text-3xl font-bold">{String(value)}</p>{label === "Kundebredde" && !noActivity && <Progress className="mt-3 h-1.5" value={48} />}<p className="mt-2 text-xs text-muted-foreground">{String(note)}</p>{detail && <p className="mt-1 text-xs text-muted-foreground">{String(detail)}</p>}{trend && <p className="mt-2 text-xs text-muted-foreground">{String(trend)}</p>}</CardContent></Card></button>)}</section>

        <section id="signals" className="scroll-mt-4 space-y-3"><div><h3 className="text-xl font-bold">Aktuelle kundesignaler</h3><p className="text-sm text-muted-foreground">Snapshot. Hver regel har sin egen tidshorisont.</p></div><Card className="overflow-hidden shadow-sm"><div className="divide-y">{signals.map((signal) => <button key={signal.id} className="grid w-full gap-3 p-4 text-left hover:bg-muted/20 lg:grid-cols-[1.2fr_1.5fr_1fr_1.2fr] lg:items-center" onClick={() => setSelectedSignal(signal)}><div><p className="font-semibold">{signal.name}</p><p className="text-xs text-muted-foreground">Segment {scenario === "missing-segment" && signal.id === "SIG-005" ? "ukendt" : signal.segment} · {signal.type}</p></div><div><p className="text-sm">{signal.reason}</p><p className="text-xs text-muted-foreground">Reglens egen horisont: {signal.horizon}</p></div><p className="text-sm"><span className="block text-xs text-muted-foreground">Sidste registrerede kontakt</span>{signal.last}</p><p className={`text-sm ${signal.meeting === "unknown" || scenario === "unknown-meeting" ? "border-l-2 border-muted-foreground/40 pl-3" : ""}`}><span className="block text-xs text-muted-foreground">Næste møde</span>{scenario === "unknown-meeting" && signal.id === "SIG-001" ? "Mødedata utilgængelig" : signal.next}</p></button>)}</div><div className="border-t p-3 text-center"><Button variant="ghost" onClick={() => setPanel("signals")}>Se alle 12</Button></div></Card></section>

        <section className="grid gap-5 xl:grid-cols-[1.4fr_1fr]"><div className="space-y-3"><div><h3 className="text-xl font-bold">Kundedækning</h3><div className="mt-2 flex gap-2"><Button size="sm" variant={customerType === "HCO" ? "default" : "outline"} onClick={() => setCustomerType("HCO")}>HCO</Button><Button size="sm" variant={customerType === "HCP" ? "default" : "outline"} onClick={() => setCustomerType("HCP")}>HCP</Button><Badge variant="outline">Uden kommende møde</Badge></div></div><Card className="overflow-hidden shadow-sm"><Table><TableHeader><TableRow><TableHead>Kunde</TableHead><TableHead>Sidste kontakt</TableHead><TableHead>Kontakter</TableHead><TableHead>Næste møde</TableHead></TableRow></TableHeader><TableBody>{customerType === "HCO" ? customers.map((row) => <TableRow key={row.name}><TableCell><span className="font-medium">{row.name}</span><span className="block text-xs text-muted-foreground">Segment {row.segment}</span></TableCell><TableCell>{row.last}<span className="block text-xs text-muted-foreground">{row.channel}</span></TableCell><TableCell>{row.contacts}</TableCell><TableCell>{row.next}</TableCell></TableRow>) : <TableRow><TableCell colSpan={4} className="py-8 text-center text-muted-foreground">HCP'er vises separat fra HCO-dækningen.</TableCell></TableRow>}</TableBody></Table></Card></div><div className="space-y-3"><h3 className="text-xl font-bold">Distrikter efter kundebehov</h3><Card className="overflow-hidden shadow-sm"><Table><TableHeader><TableRow><TableHead>Distrikt</TableHead><TableHead>Dækning</TableHead><TableHead>Uden møde</TableHead></TableRow></TableHeader><TableBody>{districts.map((row) => <TableRow key={row.name}><TableCell>{row.name}</TableCell><TableCell>{row.coverage}</TableCell><TableCell>{row.missing}</TableCell></TableRow>)}</TableBody></Table><div className="border-t p-4"><p className="font-medium">Kommende 28 dage — 17 møder hos 14 unikke kunder</p><p className="mt-1 text-xs text-muted-foreground">Uge 41: 6 · uge 42: 5 · uge 43: 4 · uge 44: 2</p></div></Card></div></section>

        <section id="themes" className="scroll-mt-4 space-y-3"><div><h3 className="text-xl font-bold">Hvad kunderne taler om</h3><p className="text-sm text-muted-foreground">{partial ? "51 af 58 debriefs er analyseret. 5 fejlet, 2 afventer." : "51 af 58 debriefs er analyseret. 5 fejlet, 2 afventer."}</p></div><Card className="overflow-hidden shadow-sm"><Table><TableHeader><TableRow><TableHead>Tema</TableHead><TableHead>Produkt</TableHead><TableHead>Debriefs</TableHead><TableHead>Andel</TableHead><TableHead>Unikke kunder</TableHead><TableHead>Ændring</TableHead></TableRow></TableHeader><TableBody>{themes.map((theme) => <TableRow key={theme.id} className="cursor-pointer" onClick={() => setSelectedTheme(theme)}><TableCell className="font-medium underline decoration-border underline-offset-4">{theme.label}</TableCell><TableCell>{theme.product}</TableCell><TableCell>{theme.count}</TableCell><TableCell>{theme.share}</TableCell><TableCell>{theme.customers}</TableCell><TableCell>{theme.change ?? <span className="text-muted-foreground">Ikke sammenlignelig</span>}</TableCell></TableRow>)}</TableBody></Table></Card></section>

        <section className="space-y-3"><h3 className="text-xl font-bold">Fremdrift mod kontaktplaner</h3><Card className="shadow-sm"><CardContent className="p-6">{scenario === "no-plan" ? <div><CalendarClock className="h-6 w-6 text-muted-foreground" /><p className="mt-3 font-semibold">Ingen kontaktplan tilgængelig for denne medarbejder</p></div> : <button className="w-full text-left" onClick={() => setPanel("plan")}><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-3xl font-bold">38 / 56</p><p className="mt-1 text-sm">planlagte besøg gennemført (68 %) · 23 kunder med mål</p></div><p className="text-xs text-muted-foreground">Planperiode 1. jul – 31. dec 2026</p></div><Progress className="mt-4 h-2" value={68} /><p className="mt-3 text-xs text-muted-foreground">Inkluderede kanaler: fysiske besøg · 4 planer udeladt: ugyldigt eller overlappende mål</p></button>}</CardContent></Card></section>

        <Accordion type="multiple" className="rounded-md border bg-card px-5"><AccordionItem value="calendar"><AccordionTrigger>Kalenderændringer</AccordionTrigger><AccordionContent><div className="grid gap-3 sm:grid-cols-3"><div><p className="text-2xl font-bold">9</p><p className="text-sm text-muted-foreground">slettede</p></div><div><p className="text-2xl font-bold">2</p><p className="text-sm text-muted-foreground">aflyste</p></div><div><p className="text-2xl font-bold">1</p><p className="text-sm text-muted-foreground">ombooket</p></div></div><p className="mt-4 text-xs text-muted-foreground">Kalenderændringer indgår ikke i de 62 registrerede kontakter.</p></AccordionContent></AccordionItem><AccordionItem value="training"><AccordionTrigger>Træning</AccordionTrigger><AccordionContent><p className="text-sm text-muted-foreground">Ingen træningsresultater i perioden.</p><div className="mt-4 rounded border p-4"><p className="font-medium">Seneste resultat: 14. mar 2026 — score 6 af 10</p><p className="mt-3 text-sm"><strong>Det gik godt:</strong> Klar forklaring af det akutte appendicitisforløb.</p><p className="mt-2 text-sm"><strong>Kan forbedres:</strong> Udforsk kirurgisk præference før materialet præsenteres.</p><p className="mt-2 text-sm"><strong>Oprindelig anbefaling:</strong> Start med ét åbent spørgsmål om det nuværende patientforløb.</p></div></AccordionContent></AccordionItem></Accordion>
      </>}
    </main>

    <Sheet open={panel !== null} onOpenChange={(open) => !open && setPanel(null)}><SheetContent className="w-full overflow-y-auto sm:max-w-xl"><SheetHeader><SheetTitle>{panel === "contacts" ? "Registrerede kontakter" : panel === "coverage" ? "Kundebredde" : panel === "documentation" ? "Dokumentation foreligger" : panel === "quality" ? "Debriefkvalitet" : panel === "signals" ? "Alle aktuelle signaler" : panel === "themes" ? "Kundetemaer" : panel === "plan" ? "Kontaktplan" : "Kilder til observationer"}</SheetTitle><SheetDescription>{option.range} · Lokale demokilder</SheetDescription></SheetHeader><div className="mt-6 space-y-5"><div><p className="text-xs font-medium text-muted-foreground">Definition</p><p className="mt-1 text-sm">Poster, der opfylder definitionen for det valgte område og de aktive filtre.</p></div><div className="flex flex-wrap gap-2"><Badge variant="outline">{employee.name}</Badge><Badge variant="outline">{employee.district}</Badge><Badge variant="outline">Appendicitis</Badge></div>{["30. sep · Lægehuset Nordbro · fysisk · dokumentation foreligger", "28. sep · Klinik Vestbro · virtuelt · importeret fra CRM", "26. sep · Søholm Klinikhus · telefon · kladde"].map((row) => <div key={row} className="rounded border p-4 text-sm">{row}</div>)}<div className="flex items-center justify-between border-t pt-4 text-sm"><Button variant="outline" size="sm" disabled>Forrige</Button><span>Side 1 af 4</span><Button variant="outline" size="sm">Næste</Button></div></div></SheetContent></Sheet>

    <Sheet open={prepOpen} onOpenChange={setPrepOpen}><SheetContent className="manager-prep-print w-full overflow-y-auto sm:max-w-2xl"><SheetHeader><SheetTitle>Forbered 1:1 · {employee.name}</SheetTitle><SheetDescription>{option.range} · Genereret 2. okt 2026 kl. 10:48</SheetDescription></SheetHeader>{scenario === "prep-error" ? <div className="mt-8 rounded-md border border-destructive/40 p-6 text-center"><AlertCircle className="mx-auto h-8 w-8 text-destructive" /><h3 className="mt-3 font-semibold">AI-generering fejlede</h3><p className="mt-2 text-sm text-muted-foreground">En deterministisk dagsorden vises i stedet, så forberedelsen kan fortsætte.</p><Button className="mt-4" onClick={() => setScenario("normal")}><RefreshCw className="mr-2 h-4 w-4" />Prøv igen</Button></div> : null}<div className="mt-6 flex gap-2 print:hidden"><Button size="sm" onClick={copyPrep}><Clipboard className="mr-2 h-4 w-4" />Kopiér som tekst</Button><Button size="sm" variant="outline" onClick={() => window.print()}><Printer className="mr-2 h-4 w-4" />Print</Button></div><div className="mt-6 rounded-md border bg-primary/5 p-5"><div className="flex items-center gap-2"><CheckCircle2 className="h-5 w-5 text-primary" /><h3 className="font-bold">Dokumenteret styrke</h3></div><p className="mt-2 text-sm leading-6">{documentedStrength}</p><button className="mt-2 text-xs text-primary underline" onClick={() => setPanel("quality")}>Kilde: QUALITY-039</button></div><div className="mt-5 space-y-4">{oneToOnePoints.map((item, index) => <Card key={item.title}><CardContent className="p-5"><Badge variant="secondary">Samtalepunkt {index + 1}</Badge><h3 className="mt-3 font-bold">{item.title}</h3><p className="mt-3 text-sm"><strong>Observation:</strong> {item.observation}</p><p className="mt-3 text-sm"><strong>Spørgsmål:</strong> “{item.question}”</p><button className="mt-3 text-xs text-primary underline" onClick={() => setPanel(index === 0 ? "signals" : index === 1 ? "themes" : "documentation")}>Kilder: {item.sources}</button></CardContent></Card>)}</div></SheetContent></Sheet>

    <Dialog open={selectedTheme !== null} onOpenChange={(open) => !open && setSelectedTheme(null)}><DialogContent><DialogHeader><DialogTitle>{selectedTheme?.label}</DialogTitle><DialogDescription>Ordrette, fiktive demoudsnit · {selectedTheme?.id}</DialogDescription></DialogHeader><div className="space-y-3">{selectedTheme?.examples.map((example, index) => <div key={example} className="rounded bg-muted/40 p-4"><p className="text-sm">“{example}”</p><p className="mt-2 text-xs text-muted-foreground">{12 + index * 6}. sep 2026 · Demo HCO {index + 1} · Dose 1</p></div>)}</div></DialogContent></Dialog>
    <Dialog open={selectedSignal !== null} onOpenChange={(open) => !open && setSelectedSignal(null)}><DialogContent><DialogHeader><DialogTitle>{selectedSignal?.name}</DialogTitle><DialogDescription>Aktuelt kundesignal · {selectedSignal?.id}</DialogDescription></DialogHeader><div className="space-y-4 text-sm">{selectedSignal?.reasons.map((reason) => <p key={reason}><strong>Hvorfor:</strong> {reason}</p>)}<p><strong>Reglens egen horisont:</strong> {selectedSignal?.horizon}</p><p><strong>Sidste registrerede kontakt:</strong> {selectedSignal?.last}</p><p><strong>Næste møde:</strong> {selectedSignal?.next}</p><Button variant="outline">Åbn kunde</Button></div></DialogContent></Dialog>
  </div>;
};

export const slugify = (name: string) => name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
export default EmployeeDetail;