import { useState } from "react";
import { MapPinned } from "lucide-react";
import { Progress } from "@/components/ui/progress";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { employeeBrickCoverage, type TeamMember } from "@/data/managerDemo";
import { ErrorBlock } from "./StateBlocks";
import { ManagerSection } from "./ManagerSection";
import { Button } from "@/components/ui/button";
export function EmployeeBrickCoverage({ member, range, noActivity, loadError, onRetry }: { member: TeamMember; range: string; noActivity: boolean; loadError: boolean; onRetry: () => void }) {
 const [showAll, setShowAll] = useState(false);
 const [sort, setSort] = useState("name");
 const rows = [...employeeBrickCoverage].map(row => ({ ...row, visited: noActivity ? 0 : row.visited })).sort((a,b) => sort === "coverage" ? a.visited / a.assigned - b.visited / b.assigned : a.name.localeCompare(b.name, "da"));
 const visited = rows.reduce((sum, row) => sum + row.visited, 0);
 return <ManagerSection id="employee-coverage" title="Mødedækning" header={<div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-start gap-3"><MapPinned className="mt-1 h-5 w-5 text-primary" /><div><h3 className="text-lg font-bold">Mødedækning</h3><p className="text-xs text-muted-foreground">Besøgte HCO'er fordelt på bricks · {range}</p></div></div><Select value={sort} onValueChange={setSort}><SelectTrigger className="h-8 w-48 bg-card" aria-label="Sortér bricks"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="name">Navn</SelectItem><SelectItem value="coverage">Laveste dækning først</SelectItem></SelectContent></Select></div>}>
 {loadError ? <ErrorBlock label="Mødedækning" onRetry={onRetry} /> : member.slug !== "christian" ? <p className="text-sm text-muted-foreground">Fordelingen på bricks er ikke tilgængelig for denne medarbejder i demoen.</p> : <><div className="mb-4 flex flex-wrap items-baseline gap-x-5 gap-y-1 text-sm text-muted-foreground"><span><span className="font-semibold text-foreground">{visited} af {member.hcosAssigned}</span> HCO'er besøgt</span><span aria-hidden="true">·</span><span><span className="font-semibold text-foreground">{rows.filter(row => row.visited > 0 && row.name !== "Uden brick").length} af {rows.filter(row => row.name !== "Uden brick").length}</span> bricks har besøg</span></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{(showAll ? rows : rows.slice(0, 6)).map(row => <div className="rounded-lg border bg-card p-4" key={row.name}><div className="flex items-baseline justify-between gap-3"><h4 className="text-sm font-semibold">{row.name}</h4><span className="shrink-0 text-sm font-semibold">{Math.round(row.visited / row.assigned * 100)} %</span></div><p className="mt-2 text-sm text-muted-foreground"><span className="font-medium text-foreground">{row.visited} / {row.assigned}</span> HCO'er besøgt</p><Progress className="mt-3 h-1.5" value={row.visited / row.assigned * 100} /><p className="mt-2 text-xs text-muted-foreground">{row.assigned - row.visited} uden besøg · {row.unsegmented} uden segmentklasse</p></div>)}</div>{rows.length > 6 && <div className="text-center"><Button variant="ghost" size="sm" onClick={() => setShowAll(value => !value)} aria-expanded={showAll}>{showAll ? "Vis færre" : "Vis mere"}</Button></div>}<p className="text-xs leading-5 text-muted-foreground">Unikke tildelte HCO'er med mindst ét fysisk besøg i perioden. Virtuelle kontakter indgår i kontakt-KPI'en, men ikke her. Hver HCO tilhører én brick; kunder uden brick vises særskilt. Fiktive demo-områder.</p></>}
 </ManagerSection>;
}
