import { Target } from "lucide-react";
import { Progress } from "@/components/ui/progress";
import { employeePlanGoals, employeeCalendarBreakdown, employeePlanSnapshot as snapshot, upcoming28, fmt, type TeamMember } from "@/data/managerDemo";
import { projectPlanPace, summarizePlan } from "@/data/employeePlanning";
import { ErrorBlock } from "@/components/manager/StateBlocks";

import { ManagerSection, ManagerSectionTitle } from "./ManagerSection";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";

type Props = { member: TeamMember; noActivity: boolean; noPlan: boolean; loadError: boolean; onRetry: () => void };

export const EmployeeActivityPanels = ({ member, noActivity, noPlan, loadError, onRetry }: Props) => {
  const plan = member.plan;
  const done = noActivity ? 0 : plan?.done ?? 0;
  const outlook = member.slug === "christian" && !noActivity ? summarizePlan(employeePlanGoals) : null;
  // Completed plan progress and calendar bookings must share the snapshot before projecting.
  const forecast = outlook && plan && !noPlan ? projectPlanPace(snapshot.done, snapshot.target, outlook.booked, snapshot.windowDays, snapshot.remainingDays) : null;
  const completionDate = forecast?.daysToTarget !== null && forecast?.daysToTarget !== undefined ? new Date(Date.parse(`${snapshot.date}T12:00:00Z`) + forecast.daysToTarget * 86400000).toLocaleDateString("da-DK", { day: "numeric", month: "long" }) : null;
  return <ManagerSection id="contact-plan" title="Kontaktplan og kommende møder" header={
    <div className="flex flex-wrap items-baseline justify-between gap-2"><div className="flex items-center gap-3"><Target className="h-5 w-5 text-primary" /><ManagerSectionTitle>Kontaktplan og kommende møder</ManagerSectionTitle></div><span className="text-sm text-muted-foreground">Plan: 1. jul – 31. dec 2026 · Status 7. okt</span></div>}>
    {loadError ? <ErrorBlock label="Kontaktplaner og kommende møder" onRetry={onRetry} /> : <>
      <div className="manager-band">
        {forecast && outlook && <div className="flex flex-wrap items-start justify-between gap-3 border-b p-4 sm:p-5">
          <div className="max-w-2xl"><h4 className={`text-sm font-semibold ${forecast.shortfall ? "text-destructive" : "text-success"}`}>{forecast.shortfall ? "Planen nås ikke med det nuværende tempo" : "Planen kan nås med det nuværende tempo"}</h4><p className="mt-1 text-xs leading-5 text-muted-foreground">{forecast.shortfall ? `Der forventes at mangle ${forecast.shortfall} besøg den 31. december.` : `Forventet måldato: ${completionDate}.`} Forudsætter gennemførte besøg og fortsat booking hos kunder med åbne mål.</p></div>
          <div className="shrink-0 text-right"><p className="text-xl font-bold tabular-nums">{forecast.projected} / {snapshot.target}</p><p className="text-xs text-muted-foreground">{forecast.percent} % · Beregnet — ikke booket</p></div>
        </div>}
        <div className="grid divide-y md:grid-cols-2 md:divide-x md:divide-y-0">
          <div className="p-4 sm:p-5"><p className="text-xs font-semibold text-muted-foreground">Gennemført mod planen</p>{noPlan || !plan ? <p className="mt-3 text-xs text-muted-foreground">Ingen kontaktplan tilgængelig.</p> : <><p className="mt-2 text-xl font-bold tabular-nums">{done}<span className="text-xs font-normal text-muted-foreground"> / {plan.planned} fysiske besøg</span></p><Progress value={done / plan.planned * 100} className="mt-3 h-1.5" /><div className="mt-2 flex justify-between gap-2 text-xs"><span>{Math.round(done / plan.planned * 100)} % gennemført</span><span className="text-muted-foreground">{plan.planned - done} besøg tilbage</span></div>{outlook && <div className="mt-4 grid grid-cols-2 gap-3 border-t pt-3"><div><p className="text-xl font-bold tabular-nums">{outlook.booked}</p><p className="text-xs text-muted-foreground">booket mod åbne mål</p></div><div><p className="text-xl font-bold tabular-nums">{outlook.unbooked}</p><p className="text-xs text-muted-foreground">endnu ikke booket</p></div></div>}<p className="mt-3 text-xs leading-5 text-muted-foreground">{plan.customers} kunder med mål · {plan.excluded} ugyldige eller overlappende mål udeladt</p></>}</div>
          <div className="p-4 sm:p-5"><p className="text-xs font-semibold text-muted-foreground">Kommende {snapshot.windowDays} dage · hele porteføljen</p>{outlook ? <><p className="mt-2 text-xl font-bold tabular-nums">{upcoming28.meetings}<span className="text-xs font-normal text-muted-foreground"> møder · {upcoming28.customers} kunder</span></p><p className="mt-1 text-xs leading-5 text-muted-foreground"><strong className="font-semibold text-foreground">{outlook.booked}</strong> af de {upcoming28.meetings} kommende møder tæller mod planens åbne mål</p><div className="mt-3 grid grid-cols-5 gap-2 border-y py-2">{upcoming28.weeks.map(([week, count]) => <div key={week} className="text-center"><p className="text-xs text-muted-foreground">{week}</p><p className="mt-1 text-sm font-semibold tabular-nums">{count}</p></div>)}</div><div className="mt-3 space-y-1.5 text-xs"><p className="flex justify-between gap-2 text-muted-foreground"><span>Øvrige fysiske besøg</span><span>{employeeCalendarBreakdown.physicalWithoutRemainingGoal}</span></p><p className="flex justify-between gap-2 text-muted-foreground"><span>Virtuelle møder</span><span>{employeeCalendarBreakdown.virtual}</span></p></div><p className="mt-3 text-xs text-muted-foreground">7. okt – 4. nov · kun besøg mod åbne mål driver prognosen.</p></> : <p className="mt-3 text-xs text-muted-foreground">Kommende møder er ikke forberedt for denne medarbejder i demoen.</p>}</div>
        </div>
        {forecast && outlook && <div className="border-t bg-muted/20 px-4 py-3 sm:px-5"><div className="flex flex-wrap items-center justify-between gap-2 text-xs"><p><strong>{fmt(forecast.dailyPace * 7)}</strong> målrettede besøg/uge booket</p><p className="text-muted-foreground"><strong className="text-foreground">{fmt(outlook.remaining / snapshot.remainingDays * 7)}</strong> besøg/uge kræves frem til 31. december</p></div><Accordion type="single" collapsible><AccordionItem value="forecast-assumptions" className="border-0"><AccordionTrigger className="py-2 text-xs">Beregning og forudsætninger</AccordionTrigger><AccordionContent className="text-xs leading-5 text-muted-foreground">{snapshot.done} gennemført + ({outlook.booked} ÷ {snapshot.windowDays} kalenderdage × {snapshot.remainingDays} dage til fristen), højst {snapshot.target}. Kun {outlook.booked} besøg er faktisk booket mod åbne mål. Øvrige fysiske og virtuelle møder indgår ikke. Fiktiv prognose — forudsætter fortsat samme tempo og fordeling på kunder med resterende mål, og tager ikke højde for ferie eller aflysninger.</AccordionContent></AccordionItem></Accordion></div>}
        {outlook && <Accordion type="single" collapsible className="border-t px-4 sm:px-5"><AccordionItem value="plan-customers" className="border-0"><AccordionTrigger className="text-xs">Se besøgsplan · kunder med åbne mål</AccordionTrigger><AccordionContent><div className="divide-y">{employeePlanGoals.map(goal => <div key={goal.customer} className="flex flex-wrap justify-between gap-2 py-2 text-xs"><span>{goal.customer}</span><span className="text-muted-foreground">{goal.remaining} besøg tilbage · {goal.bookedPhysical ? "Booket fysisk besøg" : "Ikke booket"}</span></div>)}</div></AccordionContent></AccordionItem></Accordion>}
      </div>
    </>}
  </ManagerSection>;
};
