import { Fragment, useState } from "react";
import { Info } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { fmt } from "@/data/managerDemo";
import { referenceSourceQuality } from "@/data/managerReference";

export function SourceQuality({ scope, compact = false }: { scope: "homepage" | "employee"; compact?: boolean }) {
  const [selected, setSelected] = useState<typeof referenceSourceQuality.homepage[number] | null>(null);
  return <div className={compact ? "flex h-full flex-col gap-2" : "space-y-3 border-t border-border/50 pt-4"}>
    <div className="flex flex-wrap items-baseline justify-between gap-2"><p className={compact ? "text-xs font-semibold text-muted-foreground" : "text-sm font-semibold"}>Debriefkvalitet efter kilde</p><span className="text-xs text-muted-foreground">Illustrativt referenceeksempel · sidste 30 dage</span></div>
    <div className={compact ? "flex flex-1 flex-col" : "grid gap-3 sm:grid-cols-2"}>{referenceSourceQuality[scope].map((row, index) => <Fragment key={row.source}>{compact && index > 0 && <span aria-hidden="true" className="mx-2 h-px shrink-0 bg-border" />}<Button variant="ghost" onClick={() => setSelected(row)} className={compact ? "-mx-2 h-auto min-h-0 w-full flex-1 items-center justify-between gap-4 whitespace-normal rounded-md px-2 py-3 text-left" : "h-auto items-start justify-between gap-3 whitespace-normal rounded-lg border bg-card p-3 text-left"}><div className="min-w-0 flex-1"><p className="text-xs font-semibold">{row.source}</p><p className={`text-xs font-normal text-muted-foreground ${compact ? "mt-0.5" : "mt-1"}`}>{row.assessed} vurderede debriefs</p></div><div className={`flex shrink-0 gap-2 ${compact ? "items-center" : "flex-col items-end"}`}><p className={row.score === null ? "text-xs font-normal text-muted-foreground" : "text-xl font-bold text-primary tabular-nums"}>{row.score === null ? "Ikke vurderet" : `${fmt(row.score)} / 10`}</p><Info className="h-3.5 w-3.5 shrink-0 text-muted-foreground" /></div></Button></Fragment>)}</div>
    <Dialog open={selected !== null} onOpenChange={open => { if (!open) setSelected(null); }}><DialogContent><DialogHeader><DialogTitle>Debriefkvalitet · {selected?.source}</DialogTitle><DialogDescription>{scope === "homepage" ? "Teamoverblik" : "Medarbejderoversigt"} · illustrativt kildeeksempel fra den vedhæftede reference</DialogDescription></DialogHeader><p className="text-sm leading-6">{selected?.score === null ? "Ingen vurderede debriefs fra denne kilde i referenceeksemplet. Det er ikke en score på nul." : `${selected?.assessed} vurderede debriefs med et gennemsnit på ${selected ? fmt(selected.score ?? 0) : ""} ud af 10.`}</p><p className="text-xs leading-5 text-muted-foreground">Vurderingen handler om dokumentationen, ikke medarbejderen eller samtalen. Kildegrupperne har forskelligt datagrundlag og er ikke en effektmåling af Jarvis versus IO Engage. Detaljerede underliggende noter er ikke med i referenceeksemplet.</p></DialogContent></Dialog>
  </div>;
}